---

################################################################
## Load stack variables
################################################################

- name: Load vars
  hosts: "*"
  tasks:
    - name: Include vars
      include_vars:
        file: "./vars/stack01.yaml"
  tags:
    - always

################################################################
## SAMPLE provisioning
################################################################

##provision
- import_playbook: sagenv-common-webmethods.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: stack01_ansible_group
    cce_provisioning_template: stack01/cce_product1/template_runtime.yaml
    cce_provisioning_properties: stack01_cce_product1_environment
    cce_provisioning_template_params:
      - name: "repo.product"
        value: "{{ cce_provisioning_products_repo_apigateway }}"
      - name: "repo.fix"
        value: "{{ cce_provisioning_fixes_repo_apigateway }}"
      - name: "fixes.apply"
        value: "ALL"
      - name: "cce_param1"
        value: "cce_param1_value"
      - name: "cce_param2"
        value: "cce_param2_value"        
      - name: "cce_param3"
        value: "cce_param3_value"
    cce_provisioning_template_params_secure:
      - name: "cce_secure_param1"
        value: "cce_secure_param1_value"
  tags:
    - install

- import_playbook: sagenv-common-webmethods-postinstall.yaml
  vars:
    cce_provisioning_inventory_hosts_pattern: stack01_ansible_group
    cce_provisioning_installed_product_names: apigateway
    cce_provisioning_installed_product_instance_names: apigateway
    cce_provisioning_validation_ports:
      - 5555
      - 9072
  tags:
    - postinstall