
#### some ansible variables to use in the playbooks

## ie. product versions
product_version_major: 10
product_version_minor: 5
product_version_full: "{{ product_version_major }}{{ product_version_minor }}"

## ie. product CCE repos
cce_provisioning_products_repo_sdc: "webMethods-{{ product_version_major }}.{{ product_version_minor }}"
cce_provisioning_fixes_repo_sdc: "Empower"